# Generated by Django 5.2.4 on 2025-07-27 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_follower'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='follower',
            name='followed',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='followers_set',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='follower',
            name='follower',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='following_set',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]