# Generated by Django 6.0.6 on 2026-06-21 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_follower_created_at_alter_follower_followed_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
